services:
  - type: web
    name: tt-tools-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PORT
        value: 5000
